services:
  redis:
    image: redis
    volumes:
      - /data/redis:/data
    restart: unless-stopped

  backend:
    build: server
    ports:
      - 25125:25125
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379/
      - PORT=25125
    depends_on:
      - redis
    restart: unless-stopped
